# Generated by Django 2.0.5 on 2018-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('TR', 'Teacher'), ('BK', 'Book')], max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
