# Generated by Django 2.0.5 on 2018-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='klass',
            field=models.IntegerField(default=0),
        ),
    ]
