# Generated by Django 2.0.5 on 2018-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20180507_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='klass',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VII')], max_length=10),
        ),
    ]
