# Generated by Django 2.0.5 on 2018-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20180507_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='klass',
            field=models.CharField(choices=[('1st', 'I'), ('2nd', 'II'), ('3rd', 'III'), ('4th', 'IV'), ('5th', 'V'), ('6th', 'VI'), ('7th', 'VII'), ('8th', 'VII')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Social-Studies', 'Social Studies'), ('English', 'English'), ('Moral-Science', 'Moral-Science')], max_length=50),
        ),
    ]
