# Generated by Django 2.0.5 on 2018-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20180507_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperid', models.CharField(max_length=5)),
                ('papername', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=50)),
                ('klass', models.CharField(max_length=10)),
                ('questions', models.ManyToManyField(to='qna.Questions')),
            ],
        ),
    ]
