# Generated by Django 2.0.5 on 2018-05-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='paperid',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
