# Generated by Django 2.0.5 on 2018-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_auto_20180529_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
